### ISSUE TITLE
FreeCad 0.18 release

### ISSUE THREAD

**Issue by lukascocula** [dcowden/cadquery#306]
Hello guys,

I have problem to find FreeCad library in FreeCad 0.18 release. Error message:

`ImportError: cadquery was unable to determine freecad library path`

Full stacktrace:

    Traceback (most recent call last):
      File "/Volumes/Praca/PyCharmProjects/step-converter-python/venv/lib/python3.7/site-packages/cadquery/freecad_impl/__init__.py", line 151, in <module>
        import FreeCAD
    ModuleNotFoundError: No module named 'FreeCAD'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Volumes/Praca/PyCharmProjects/step-converter-python/Main.py", line 5, in <module>
        from client.PartClient import convert
      File "/Volumes/Praca/PyCharmProjects/step-converter-python/client/PartClient.py", line 1, in <module>
        from cqparts import Part
      File "/Volumes/Praca/PyCharmProjects/step-converter-python/venv/lib/python3.7/site-packages/cqparts/__init__.py", line 77, in <module>
        from .component import Component
      File "/Volumes/Praca/PyCharmProjects/step-converter-python/venv/lib/python3.7/site-packages/cqparts/component.py", line 2, in <module>
        from .constraint import Mate
      File "/Volumes/Praca/PyCharmProjects/step-converter-python/venv/lib/python3.7/site-packages/cqparts/constraint/__init__.py", line 12, in <module>
        from .mate import Mate
      File "/Volumes/Praca/PyCharmProjects/step-converter-python/venv/lib/python3.7/site-packages/cqparts/constraint/mate.py", line 3, in <module>
        from ..utils.geometry import CoordSystem
      File "/Volumes/Praca/PyCharmProjects/step-converter-python/venv/lib/python3.7/site-packages/cqparts/utils/__init__.py", line 18, in <module>
        from .geometry import CoordSystem
      File "/Volumes/Praca/PyCharmProjects/step-converter-python/venv/lib/python3.7/site-packages/cqparts/utils/geometry.py", line 1, in <module>
        import cadquery
      File "/Volumes/Praca/PyCharmProjects/step-converter-python/venv/lib/python3.7/site-packages/cadquery/__init__.py", line 2, in <module>
        from .freecad_impl.geom import Plane,BoundBox,Vector,Matrix,sortWiresByBuildOrder
      File "/Volumes/Praca/PyCharmProjects/step-converter-python/venv/lib/python3.7/site-packages/cadquery/freecad_impl/__init__.py", line 153, in <module>
        path = _fc_path()
      File "/Volumes/Praca/PyCharmProjects/step-converter-python/venv/lib/python3.7/site-packages/cadquery/freecad_impl/__init__.py", line 145, in _fc_path
        raise ImportError('cadquery was unable to determine freecad library path')
    ImportError: cadquery was unable to determine freecad library path

By my investigation, there was changed path from `/Applications/FreeCAD.app/Contents/lib` to `/Applications/FreeCAD.app/Contents/Resources/lib` in darwin (MAC) platform.
Place in code: [cadquery/freecad_impl/__init__.py](https://github.com/dcowden/cadquery/blob/master/cadquery/freecad_impl/__init__.py#L138)

I am not sure about other platforms.

Thank you.

**Comment by jmwright** [comment]
@lukascocula Thanks for reporting this. I've added this new path to the list in `freecad_impl/__init__.py` on the master branch.

Please note that the [CadQuery 2.0](https://github.com/CadQuery/cadquery) repo is where almost all development will happen moving forward. CadQuery 1.0 (this repo) will probably not see any major updates moving forward.
